=== kwSeo/RDF-Object-Mapper/sample.old/mapper-prototype.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT mapper (resultMap*, select*, ask*)>
	<!ATTLIST mapper namespace CDATA "default">
	
	<!ELEMENT resultMap (result+, relation*)>
		<!ATTLIST resultMap id CDATA #REQUIRED>
		<!ATTLIST resultMap type CDATA #REQUIRED>
		
		<!ELEMENT relation (result+)>
			<!ATTLIST relation id CDATA #REQUIRED>
			<!ATTLIST relation type CDATA #REQUIRED>
			
		<!ELEMENT result EMPTY> 
			<!ATTLIST result column CDATA #REQUIRED>
			<!ATTLIST result field CDATA #REQUIRED>
			
	<!ELEMENT select (#PCDATA)>
		<!ATTLIST select id CDATA #REQUIRED>
		<!ATTLIST select resultType CDATA #REQUIRED>

	<!ELEMENT ask (#PCDATA)>
		<!ATTLIST ask id CDATA #REQUIRED>

=== kwSeo/RDF-Object-Mapper/src/resources/sample/mapper-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mapper
	SYSTEM "/home/kwseo/git/RDF-Object-Mapper/src/resources/sample/mapper-prototype.dtd">

<mapper namespace="afgm.seo.test">
	<resultMap type="team.afgm.bean.Person" id="personMap">
		<result column="name" field="name"/>
		<result column="age" field="age"/>
		<result column="tel" field="tel"/>
	</resultMap>

	<select id="testSelect" resultType="personMap">
		SELECT ?name ?age ?tel
		WHERE {
			?x 	a	hc:Person;
				hc:name	?name;
				hc:age	?age;
				hc:tel	?tel.
			FILTER( ?age > 19)
		}
	</select>
	
	<select id="testSelect2" resultType="String">
		SELECT ?name
		WHERE {
			?x 	a 		hc:Person;
				hc:name	?name.
		}
	</select>
	
	<select id="testSelect3" resultType="String">
		select distinct ?Concept where {[] a ?Concept} LIMIT 100
	</select>
</mapper>
