=== kwSeo/RDF-Object-Mapper/src/resources/sample/namespace.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT configuration (endpoints, namespaces, mappers)>
	<!ELEMENT endpoints (endpoint+)>
		<!ELEMENT endpoint (property+)>
			<!ATTLIST endpoint type (file|url) #REQUIRED>
			<!ATTLIST endpoint default CDATA "false" >
			<!ATTLIST endpoint id CDATA #REQUIRED>
			<!ELEMENT property (#PCDATA)>
				<!ATTLIST property name CDATA #REQUIRED>
				
	<!ELEMENT namespaces (namespace+)>
		<!ELEMENT namespace EMPTY>
			<!ATTLIST namespace prefix CDATA #REQUIRED>
			<!ATTLIST namespace url CDATA #REQUIRED>
	<!ELEMENT mappers (mapper+)>
		<!ELEMENT mapper EMPTY>
			<!ATTLIST mapper resource CDATA #REQUIRED>

=== kwSeo/RDF-Object-Mapper/sample/context-config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration 
	SYSTEM "namespace.dtd">
	
<configuration>
	<endpoints>
		<endpoint id="testFile" type="file">
			<property name="path">sample/test.rdf</property>			
		</endpoint>
		
		<endpoint id="dbpedia" type="url" default="true">
			<property name="path">http://ko.dbpedia.org/sparql</property>
		</endpoint>
	</endpoints>
	
	<namespaces>
		<namespace prefix="hc" url="http://sample.com#"/>
		<namespace prefix="foaf" url="ttp://xmlns.com/foaf/0.1/"/>
	</namespaces>
	
	<mappers>
		<mapper resource="team/afgm/rdfom/test-sample1.xml"/>
		<mapper resource="team/afgm/rdfom/test-sample2.xml"/>
	</mappers>
</configuration>

=== kwSeo/RDF-Object-Mapper/sample/context-config2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE configuration 
	SYSTEM "namespace.dtd">
	
<configuration>
	<endpoints>
		<endpoint id="testFile" type="file">
			<property name="path">sample/test.rdf</property>			
		</endpoint>
		<endpoint id="testFile2" type="file">
			<property name="path">sample/test2.rdf</property>
		</endpoint>
		<endpoint id="dbpedia" type="url" default="true">
			<property name="url">http://ko.dbpedia.org/sparql</property>
		</endpoint>
	</endpoints>
	
	<namespaces>
		<namespace prefix="hc" url="http://sample.com#"/>
		<namespace prefix="foaf" url="http://xmlns.com/foaf/0.1/"/>
		<namespace prefix="vcard" url="http://www.w3.org/2001/vcard-rdf/3.0#"/>
		<namespace prefix="info" url="http://somewhere/peopleInfo#"/>
	</namespaces>
	
	<mappers>
		<mapper resource="sample/mapper-sample.xml"/>
		<mapper resource="sample/mapper-sample2.xml"/>
	</mappers>
</configuration>
